apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_USER: YWRtaW4=  # Base64 encoded value of 'admin'
  DB_HOST: ZWNvbWRi  # Base64 encoded value of 'ecomdb'
  DB_PASSWORD: YWRtaW4xMjM=  # Base64 encoded value of 'admin123'
  DB_NAME: ZWNvbWRi  # Base64 encoded value of 'ecomdb'
