apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb  # Name of the Deployment
  labels:
    app: db  # Label to identify the Deployment
spec:
  replicas: 1  # Number of replicas (instances) of the pod
  template:
    metadata:
      labels:
        app: db  # Labels for pods created by this template
    spec:
      initContainers:
      - name: init-cleanup  # Name of the init container
        image: busybox  # Docker image for the init container
        command: ["sh", "-c", "rm -rf /var/lib/mysql/lost+found"]  # Command to clean up the directory
        volumeMounts:
        - name: mysql-data  # Name of the volume to mount
          mountPath: /var/lib/mysql  # Mount path inside the container
      containers:
      - name: vprodb  # Name of the container
        image: saduasar/vprofiledb  # Docker image for the container
        env:
          - name: MYSQL_ROOT_PASSWORD  # Name of the environment variable
            valueFrom:
              secretKeyRef:
                name: dbsecret  # Name of the Secret
                key: password  # Key in the Secret
        ports:
        - containerPort: 3306  # Port to expose on the container
        volumeMounts:
        - name: mysql-data  # Name of the volume to mount
          mountPath: /var/lib/mysql  # Mount path inside the container
      nodeSelector:
        nodezone: us-east-1a  # Selects nodes in the specified zone
      volumes:
      - name: mysql-data  # Name of the volume
        awsElasticBlockStore:
          volumeID: vol-0a3df31cace67dbb5  # ID of the AWS EBS volume
          fsType: ext4  # File system type
  selector:
    matchLabels:
      app: db  # Selector to match pods managed by this Deployment

