apiVersion: v1
kind: Service
metadata:
  name: ecommapp  # Name of the Service
spec:
  selector:
    app: ecommapp  # Selects pods with the label "app: vproapp"
  type: LoadBalancer  # Exposes the Service externally using a LoadBalancer
  ports:
    - protocol: TCP  # Protocol used for the ports
      port: 80       # Port exposed on the Service
      targetPort: 80  # Port on the pods that the Service forwards traffic to
      # Specify the targetPort where the application in the pods is listening
      # nodePort: 32000

