apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommdb  # Name of the Deployment
  labels:
    app: ecommdb  # Label to identify the Deployment
spec:
  replicas: 1  # Number of replicas (instances) of the pod
  template:
    metadata:
      labels:
        app: ecommdb  # Labels for pods created by this template
    spec:
      initContainers:
      - name: init-cleanup  # Name of the init container
        image: busybox  # Docker image for the init container
        command: ["sh", "-c", "rm -rf /var/lib/mysql/lost+found"]  # Command to clean up the directory
        volumeMounts:
        - name: mysql-data  # Name of the volume to mount
          mountPath: /var/lib/mysql  # Mount path inside the container
      containers:
      - name: ecommdb  # Name of the container
        image: saduasar/ecommdb:v1  # Docker image for the container
        env:
          - name: MYSQL_ROOT_PASSWORD  # Name of the environment variable
            valueFrom:
              secretKeyRef:
                name: dbsecret  # Name of the Secret
                key: db_root_password  # Key in the Secret
          - name: MYSQL_PASSWORD   
            valueFrom:
              secretKeyRef:
                name: dbsecret  # Name of the Secret
                key: db_password
          - name: MYSQL_USER   
            valueFrom:
              secretKeyRef:
                name: dbsecret  # Name of the Secret
                key: db_user
        ports:
        - containerPort: 3306  # Port to expose on the container
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-data
            readOnly: false
      volumes:
      - name: mysql-data
    # mount /data/foo, but only if that directory already exists
        hostPath:
          path: /data # directory location on host
          type: DirectoryOrCreate # this will create the dir /data if it doesn't exist on the host machine.
  selector:
    matchLabels:
      app: ecommdb  # Selector to match pods managed by this Deployment

