apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomdb  # Name of the Deployment
  labels:
    app: ecomdb  # Label to identify the Deployment
spec:
  replicas: 1  # Number of replicas (instances) of the pod
  template:
    metadata:
      labels:
        app: ecomdb  # Labels for pods created by this template
    spec:
      containers:
      - name: ecomdb  # Name of the container
        image: saduasar/ecommdb:v1  # Docker image for the container
        env:
          - name: MYSQL_ROOT_PASSWORD  # Name of the environment variable
            valueFrom:
              secretKeyRef:
                name: dbsecret  # Name of the Secret
                key: db_root_password  # Key in the Secret

          - name: MYSQL_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: dbsecret  # Name of the Secret
                key: db_password

          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: dbsecret  # Name of the Secret
                key: db_user

          - name: MYSQL_DATABASE
            value: "ecomdb"
        ports:
        - containerPort: 3306  # Port to expose on the container
  selector:
    matchLabels:
      app: ecomdb  # Selector to match pods managed by this Deployment

