apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ecommapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ecommapp
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

