apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq01  # Name of the Deployment
  labels:
    app: mq  # Label to identify the Deployment
spec:
  replicas: 1  # Number of replicas (instances) of the pod
  template:
    metadata:
      labels:
        app: mq  # Labels for pods created by this template
    spec:
      containers:
      - name: vpromq01  # Name of the container
        image: rabbitmq  # Docker image for the container (assuming it's the official RabbitMQ image)
        ports:
        - containerPort: 15672  # Port to expose on the container (RabbitMQ Management UI)
  selector:
    matchLabels:
      app: mq  # Selector to match pods managed by this Deployment

