apiVersion: v1
kind: Service
metadata:
  name: vpromq01  # Name of the Service
spec:
  selector:
    app: mq  # Selects pods with the label "app: mq"
  ports:
    - protocol: TCP  # Protocol used for the ports
      port: 15672    # Port exposed on the Service
      targetPort: 15672  # Port on the pods that the Service forwards traffic to
      # Specify the targetPort where the application in the pods is listening
  type: ClusterIP  # Type of the Service, ClusterIP exposes the Service internally within the cluster

